server:
  port: 8001
  servlet:
    context-path: /user
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sillyordering_user?&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456789
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: redis
  redis:
    port: 6379
    host: localhost
    password: 123456789
  sleuth:
    sampler:
      probability: 1.0
      rate: 30
  zipkin:
    base-url: http://localhost:13001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7777/eureka
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 6
mybatis:
  mapper-locations: classpath:/mapper/*.xml
bean:
  conf:
    snowflake:
      mid: 10